/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppNurseRouteImport } from './routes/_app/nurse'
import { Route as AppDoctorRouteImport } from './routes/_app/doctor'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppModuleNameRouteImport } from './routes/_app/module.$name'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNurseRoute = AppNurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorRoute = AppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleNameRoute = AppModuleNameRouteImport.update({
  id: '/module/$name',
  path: '/module/$name',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/doctor': typeof AppDoctorRoute
  '/nurse': typeof AppNurseRoute
  '/module/$name': typeof AppModuleNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/doctor': typeof AppDoctorRoute
  '/nurse': typeof AppNurseRoute
  '/module/$name': typeof AppModuleNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/doctor': typeof AppDoctorRoute
  '/_app/nurse': typeof AppNurseRoute
  '/_app/module/$name': typeof AppModuleNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/admin' | '/doctor' | '/nurse' | '/module/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin' | '/doctor' | '/nurse' | '/module/$name'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/doctor'
    | '/_app/nurse'
    | '/_app/module/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/nurse': {
      id: '/_app/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof AppNurseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor': {
      id: '/_app/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/module/$name': {
      id: '/_app/module/$name'
      path: '/module/$name'
      fullPath: '/module/$name'
      preLoaderRoute: typeof AppModuleNameRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDoctorRoute: typeof AppDoctorRoute
  AppNurseRoute: typeof AppNurseRoute
  AppModuleNameRoute: typeof AppModuleNameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDoctorRoute: AppDoctorRoute,
  AppNurseRoute: AppNurseRoute,
  AppModuleNameRoute: AppModuleNameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
